apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-pods
  template:
    metadata:
      name: my-pods
      labels:
        app: my-pods  
    spec:
      containers:
        - name: ubuntu-container
          image: ubuntu
          command: ["/bin/sh", "-c", "apt-get update && apt-get install -y stress-ng && while true; do stress-ng --cpu 1; done"]
          resources:
            requests:
              cpu: "0.05"
            limits:
              cpu: "0.05"