apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-apache
  labels:
    app: php-apache
spec:
  selector:
    matchLabels:
      app: php-apache-pod
  template: 
    metadata:
      labels:
        app: php-apache-pod
    spec:
      containers:
        - name: php-apache-container
          image: registry.k8s.io/hpa-example
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 200m
            limits:
              cpu: 500m
---
apiVersion: v1
kind: Service
metadata:
  name: test-service
  labels:
    app: php-apache
spec:
  type: NodePort
  selector:
    app: php-apache-pod
  ports:
    - protocol: TCP
      port: 80
      nodePort: 30080  