apiVersion: v1
kind: Pod
metadata:
  name: tolerated-pod
  labels:
    app: nginx-pod
spec:
  containers:
    - name: nginx-container
      image: nginx
      ports:
        - protocol: TCP
          containerPort: 80
  tolerations:
    - key: "gpu"
      operator: "Equal"
      value: "True"
      effect: "PreferNoSchedule"
  # nodeSelector:
  #   cpu: high
