apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-cd-1
  namespace: argo-cd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  source:
    repoURL: https://github.com/udayvarmora07/Kubernetes-Practice.git
    targetRevision: HEAD
    path: 21-helm/mysqldb
  syncPolicy:
    automated:
      selfHeal: true
      prune: true