apiVersion: v1
kind: Service
metadata:
  # name: {{ include "mysqldb.fullname" . }}
  name: headless-service
  labels:
    {{- include "mysqldb.labels" . | nindent 4 }}
spec:
  clusterIP: None
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
  selector:
    {{- include "mysqldb.selectorLabels" . | nindent 4 }}
    app: mysql
