apiVersion: v1
kind: LimitRange
metadata:
  name: test-limitrange
  namespace: test-ns
spec:
  limits:
    - type: Container
      min:
        cpu: 100m
        memory: 128Mi
      max:
        cpu: 2
        memory: 2Gi
      default:
        cpu: 500m
        memory: 512Mi
      defaultRequest:
        cpu: 200m
        memory: 256Mi