apiVersion: v1
kind: ResourceQuota
metadata:
  name: test-resourcequota
  namespace: test-ns
spec:
  hard:
    pods: 5
    requests.cpu: "4"
    requests.memory: "8Gi"
    limits.cpu: "10"
    limits.memory: "16Gi"