apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: customconfigmaps.uday.com
spec:
  group: uday.com
  names:
    kind: CustomConfigMap
    plural: customconfigmaps
    shortNames:
      - ccm
  scope: Namespaced
  versions:
    - name: v1 
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            apiVersion:
              type: string
            kind:
              type: string
            metadata:
              type: object
              properties:
                name:
                  type: string
            spec:
              type: object
              properties:
                data:
                  type: string
