---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: my-secret
  namespace: default
spec:
  encryptedData:
    MYSQL_ROOT_PASSWORD: AgCOHbThQA2vKUAhIK2q5ZIXMd2iiGuxYMKHO9VR2EXXqOHdwKn1URx5EHSL8b1eW8nBqgIPtKfo+1Ryl2iFfqFpm9AeNH0lNzOFGLy+YvvxWE5Pxc69i7d8auXnkz/9d8ItDVJwMMNSzvghPhpbXcecyrP4hwYAJHQxeYNqEZTCTMlqQ/CFOyBU49GoYdEnxVmsnU7skn07vVYJMMtBJMeO/JxFOwsPBzMV8DmcL+jm5ZTX6G8FKKWaWZ2K5xTmDeMqjY11OyuiHec22AOxFOZHe3m2+CyLR68ada1UUxnYfiYJ4E1alQvMwCs6fKeDmxCKnu1y8agsyEKNz0RWRP0BCZJ8OpvSKD5nicT3uHV1CbSRKnCHVR9qe2IZXs4pBid5B3piI01ndBkJAMABu+qPhoZgzIli/yHWLml602o4Gny+T1uVf7o8c2wp+0Ar3eOqkvoNesBJkFmPKr5OyxxeHbz1Lco1glNxjvQMZEAcpRLmBiSg/lxFjdTN0LFaKW4wqFcbo//of0LwkDbG+nupe5e+yPCNBE7gThRaZ9wzYdko9SrA84PVEB8kFKa+JxX8M5F20SuWSz4TWAGg0haNgMLfQZO8eSutqc4xai5ZbcqGRjzDZHX8em/VNtHgqsvnem/gbMCPDBUykJGMegeVO82waHHvb22pRodZcPMiQSnmcsWnWk7fFK4r06rQIjuLqmkl
  template:
    metadata:
      creationTimestamp: null
      name: my-secret
      namespace: default
