apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-0
  labels:
    type: local
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: static-storageclass
  capacity:
    storage: 500Mi
  hostPath:
    path: /opt/data/mongodb-0
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-1
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: static-storageclass
  capacity:
    storage: 500Mi
  hostPath:
    path: /opt/data/mongodb-1
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-2
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: static-storageclass
  capacity:
    storage: 500Mi
  hostPath:
    path: /opt/data/mongodb-2
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-3
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: static-storageclass
  capacity:
    storage: 500Mi
  hostPath:
    path: /opt/data/mongodb-3
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-4
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: static-storageclass
  capacity:
    storage: 500Mi
  hostPath:
    path: /opt/data/mongodb-4
  persistentVolumeReclaimPolicy: Retain