apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: monogodb-statefulset
spec:
  serviceName: headless-service
  replicas: 3
  selector:
    matchLabels:
      app: mongodb-pod
  template:
    metadata:
      labels:
        app: mongodb-pod
    spec:
      containers:
        - name: mongodb-container
          image: mongo:4.4
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongo-volume
              mountPath: /data/db
  volumeClaimTemplates:
    - metadata:
        name: mongo-volume
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: static-storageclass
        resources:
          requests:
            storage: 500Mi