apiVersion: v1
kind: Pod
metadata:
  name: affinity-pod
  labels:
    app: nginx-pod
spec:
  containers:
    - name: nginx-container
      image: nginx
  # affinity:
  #   nodeAffinity:
  #     requiredDuringSchedulingIgnoredDuringExecution:
  #       nodeSelectorTerms:
  #         - matchExpressions:
  #             - key: disktype
  #               operator: In
  #               values:
  #               - SSD

  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - preference:
            matchExpressions:
              - key: disktype
                operator: In
                values:
                - ABC
          weight: 2