apiVersion: apps/v1
kind: Deployment
metadata:
  name: resource-hog
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80
              protocol: TCP
          resources:
            requests:
              cpu: "500m"
              memory: "256Mi"