apiVersion: v1
kind: Pod
metadata:
  name: high-priority-pod
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80
          protocol: TCP
      resources:
        requests:
          memory: "128Mi"
          cpu: "4000m"
  priorityClassName: high-priority