apiVersion: v1
kind: Pod
metadata:
  name: init-sidecar-pod
  labels:
    app: init-sidecar-pod
spec:
  containers:
    - name: busybox-container
      image: busybox:latest
      command: ["sh", "-c", "echo the app is running && sleep 3600"]
      env:
        - name: firstname
          value: kubernetes
  initContainers:
    - name: busybox-init
      image: busybox:latest
      command: ["sh", "-c"]
      args: ['until nslookup myservice.default.svc.cluster.local; do echo waiting for service to be up; sleep 2; done']