apiVersion: v1
kind: Pod
metadata:
  name: memory-pod2
  namespace: mem-example
spec:
  containers:
    - name: polinux-container2
      image: polinux/stress
      resources:
        requests:
          memory: "100Mi"
        limits:
          memory: "200Mi"
      command: ["stress"]
      args: ["--vm", "1", "--vm-bytes", "250M", "--vm-hang", "1"]