apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysqldb
spec:
  replicas: 1
  serviceName: headless-service
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:8.0
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: MYSQL_ROOT_PASSWORD
                  name: my-secret
          ports:
            - containerPort: 3306
              protocol: TCP
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mysql-volume
      # nodeName: kind-cluster1-worker2
  volumeClaimTemplates:
    - metadata:
        name: mysql-volume
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: static-storage-class
        resources:
          requests:
            storage: "1Gi"