apiVersion: v1
kind: Pod
metadata:
  name: test-pod
spec:
  volumes:
    - name: target-volume
      persistentVolumeClaim:
        claimName: test-pvc
  containers:
    - name: nginx-container
      image: nginx
      ports:
        - name: http
          protocol: TCP
          containerPort: 80
      volumeMounts:
        - name: target-volume
          mountPath: "/usr/share/nginx/html"
      env:
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: aws-secret
              key: aws_access_key_id
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: aws-secret
              key: aws_secret_access_key
