apiVersion: v1
kind: PersistentVolume
metadata:
  name: test-pv
  labels:
    app: pv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: "/home/uday/Kubernetes/pv-volume"