apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node
  template:
    metadata:
      labels:
        app: node
    spec:
      containers:
        - name: backend
          image: uday0710/node-backend:05
          ports:
            - containerPort: 80
              protocol: TCP
          env:
            - name: MYSQL_HOST
              valueFrom:
                configMapKeyRef:
                  key: MYSQL_HOST7
                  name: node-configmap
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  key: MYSQL_USER7
                  name: node-secret
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: MYSQL_PASSWORD7
                  name: node-secret
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  key: MYSQL_DATABASE7
                  name: node-configmap
          resources:
            requests:
              cpu: "200m"
            limits:
              cpu: "500m"