apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "backend.fullname" . }}-config
  labels:
    {{- include "backend.labels" . | nindent 4 }}
data:
  MYSQL_DATABASE7: {{ .Values.myAppConfig.MYSQL_DATABASE | quote }}