apiVersion: v1
kind: Secret
metadata:
  name: {{ include "backend.fullname" . }}-my-secret
  labels:
    {{- include "backend.labels" . | nindent 4 }}
type: Opaque
data:
  # Sensitive data goes here. Avoid storing directly in Git for production.
  MYSQL_USER7: {{ .Values.secret.user | b64enc | quote }}
  MYSQL_PASSWORD7: {{ .Values.secret.password | b64enc | quote }}